### ISSUE TITLE
スナップ機能の実装

### ISSUE THREAD

**Issue by pklion** [hebiiro/AviUtl-Plugin-UniteWindow#1]
個別で設定できるボーダー同士を、簡単に同じ位置にできるようにしていただきたいです。

**Comment by hebiiro** [comment]
ボーダーが常に十字になるようにするということですか？

**Comment by pklion** [comment]
ボーダーの形がある程度十字に近づいたときに十字にする機能、といった説明のほうがわかりやすいですね…すみません

**Comment by pklion** [comment]
更新確認しました。対応本当にありがとうございました(o*｡_｡)o
